name: anatel_dbt
version: "1.0.0"

profile: anatel_dbt

model-paths: ["models"]
seed-paths: ["seeds"]
snapshot-paths: ["snapshots"]
macro-paths: ["macros"]
test-paths: ["tests"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

models:
  anatel_dbt:
    staging:
      +materialized: view
    marts:
      +materialized: table