name: anatel_dbt
version: "1.0.0"

profile: anatel_dbt

model-paths: ["dbt/models"]
seed-paths: ["dbt/seeds"]
snapshot-paths: ["dbt/snapshots"]
macro-paths: ["dbt/macros"]
test-paths: ["dbt/tests"]

# target-path: "dbt/target"

clean-targets:
  - "dbt/target"
  - "dbt/dbt_packages"

models:
  anatel_dbt:
    staging:
      +materialized: view
      anatel:
        +tags: ["staging", "anatel"]
    marts:
      +materialized: table
      +tags: ["mart", "anatel"]
