version: 2

models:
  - name: stg_anatel_ida_smp
    columns:
      - name: grupo_economico
        tests:
          - not_null

      - name: variavel
        tests:
          - not_null

      - name: competencia
        tests:
          - not_null

      - name: valor
        tests:
          - not_null

      - name: record_hash
        tests:
          - not_null